### ISSUE TITLE
UWSGI Service does not start

### ISSUE THREAD

**Issue by HyperCriSiS** [YunoHost-Apps/searx_ynh#111]
Hi,

the uwsgi service does not start. Here is the log:

`b"ERROR:searx.search:engine torrentz : requests exception(search duration : 0.0720639228821 s, timeout: 10.0 s) : HTTPSConnectionPool(host='torrentz2.eu', port=443): Max retries exceeded with url: /search?p=0&f=github+yunohost+sear (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3e5837750>: Failed to establish a new connection: [Errno -2] Name or service not known',))"
b'Traceback (most recent call last):'
b'  File "/opt/yunohost/searx/searx/search.py", line 160, in search_one_http_request_safe'
b'    search_results = search_one_http_request(engine, query, request_params)'
b'  File "/opt/yunohost/searx/searx/search.py", line 93, in search_one_http_request'
b'    response = send_http_request(engine, request_params)'
b'  File "/opt/yunohost/searx/searx/search.py", line 77, in send_http_request'
b"    return req(request_params['url'], **request_args)"
b'  File "/opt/yunohost/searx/searx/poolrequests.py", line 133, in get'
b"    return request('get', url, **kwargs)"
b'  File "/opt/yunohost/searx/searx/poolrequests.py", line 109, in request'
b'    response = session.request(method=method, url=url, **kwargs)'
b'  File "/opt/yunohost/searx/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request'
b'    resp = self.send(prep, **send_kwargs)'
b'  File "/opt/yunohost/searx/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send'
b'    r = adapter.send(request, **kwargs)'
b'  File "/opt/yunohost/searx/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send'
b'    raise ConnectionError(e, request=request)'
b"ConnectionError: HTTPSConnectionPool(host='torrentz2.eu', port=443): Max retries exceeded with url: /search?p=0&f=github+yunohost+sear (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3e5837750>: Failed to establish a new connection: [Errno -2] Name or service not known',))"
b'WARNING:searx.search:engine timeout: seedpeer'
b'Sun Dec 27 03:31:21 2020 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /sx/?preferences=eJx1VE2P0zAQ_TXkEhUBe-CUAwIhVkLaFe1ytSb2JBlie4LttBt-PeM2aZNlOTSVx_Px3vPMBIyjTVGxVx5PKkFdfQUbsTBMKmBke8RQRU27bqzfplNhwbcjtFih3z3tC8saLFZGAihCbdGowY4t-Vj9JLez1KPqOPU4xTcfPj8M6HNWKaks-f5atw58ihhy_ex37xvylFBFHdjaJfKT1hij-vJwL0lOQRwKcoJFDYGfpxk4jIk1u8FiwiomCGkQlyJCgxEh6K56V6QOHVYcNYQC_Rb2Hm2jBAAHB4nYZzyHALoXeE8_vktlx6KJWL8dDo_7BYmc9-f0mZKGhC2HSUW0qNNNG_RSA2PVk-5BqKiGLOYKTUAsIzfpBAFLQ0HCcgJFSW6PDEmpyJrAlg4NgRjJg1JHMsg5wejjYCF2EpElySat9S4dVz4ttQIDouRq0WOArGwHdYD8mWs1JjCZGzI_AaySmlH3-dfyOsmVz60Wc2uxFExT6cZIWqnzn1xN4A0-r8NbxD6RwzhjuNRc_Gvy7dobdBt5_F8tPhKugbx_XqFfQv8xLGxRGjGzv1VrILBwlS7N95ZErTCV-T5S3MCSx6cjllurH9xMqqZUi3CY5vMEHW9EbIKMBIFewbswewXOzYBpcuxlmjZuMPSloxB4edbE_cSJY8c9-Ju2F6WvYjUBHGSOOIe5yUm_C-EUwEcrfb0Rx_Evebq1hWVQAw686u1by5QXYiuCl_qL5wuQV1gv7It7xD8e3GutsdC7TLxmg2X-zKTe3919fN7MRbJQz5fGtKXB8_7J0_9ql5_TXzfHMtQBjaHNbP0-gd8YFpcXo7xuYBiGjXZGFt8rGeZ-XI5XQa8b7xpUOEwdm-rxYX8o5s0kI1ItJRa38zrcxTTJPrfcUhbsuDMQ-r-Q-VAY&q=github+yunohost+sear (ip 93.236.2.48) !!!'
b'Sun Dec 27 03:31:21 2020 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /sx/?preferences=eJx1VE2P0zAQ_TXkEhUBe-CUAwIhVkLaFe1ytSb2JBlie4LttBt-PeM2aZNlOTSVx_Px3vPMBIyjTVGxVx5PKkFdfQUbsTBMKmBke8RQRU27bqzfplNhwbcjtFih3z3tC8saLFZGAihCbdGowY4t-Vj9JLez1KPqOPU4xTcfPj8M6HNWKaks-f5atw58ihhy_ex37xvylFBFHdjaJfKT1hij-vJwL0lOQRwKcoJFDYGfpxk4jIk1u8FiwiomCGkQlyJCgxEh6K56V6QOHVYcNYQC_Rb2Hm2jBAAHB4nYZzyHALoXeE8_vktlx6KJWL8dDo_7BYmc9-f0mZKGhC2HSUW0qNNNG_RSA2PVk-5BqKiGLOYKTUAsIzfpBAFLQ0HCcgJFSW6PDEmpyJrAlg4NgRjJg1JHMsg5wejjYCF2EpElySat9S4dVz4ttQIDouRq0WOArGwHdYD8mWs1JjCZGzI_AaySmlH3-dfyOsmVz60Wc2uxFExT6cZIWqnzn1xN4A0-r8NbxD6RwzhjuNRc_Gvy7dobdBt5_F8tPhKugbx_XqFfQv8xLGxRGjGzv1VrILBwlS7N95ZErTCV-T5S3MCSx6cjllurH9xMqqZUi3CY5vMEHW9EbIKMBIFewbswewXOzYBpcuxlmjZuMPSloxB4edbE_cSJY8c9-Ju2F6WvYjUBHGSOOIe5yUm_C-EUwEcrfb0Rx_Evebq1hWVQAw686u1by5QXYiuCl_qL5wuQV1gv7It7xD8e3GutsdC7TLxmg2X-zKTe3919fN7MRbJQz5fGtKXB8_7J0_9ql5_TXzfHMtQBjaHNbP0-gd8YFpcXo7xuYBiGjXZGFt8rGeZ-XI5XQa8b7xpUOEwdm-rxYX8o5s0kI1ItJRa38zrcxTTJPrfcUhbsuDMQ-r-Q-VAY&q=github+yunohost+sear (93.236.2.48)'
b'IOError: write error'
b'[pid: 3315|app: 0|req: 7/25] 93.236.2.48 () {48 vars in 3400 bytes} [Sun Dec 27 03:31:11 2020] GET /sx/?preferences=eJx1VE2P0zAQ_TXkEhUBe-CUAwIhVkLaFe1ytSb2JBlie4LttBt-PeM2aZNlOTSVx_Px3vPMBIyjTVGxVx5PKkFdfQUbsTBMKmBke8RQRU27bqzfplNhwbcjtFih3z3tC8saLFZGAihCbdGowY4t-Vj9JLez1KPqOPU4xTcfPj8M6HNWKaks-f5atw58ihhy_ex37xvylFBFHdjaJfKT1hij-vJwL0lOQRwKcoJFDYGfpxk4jIk1u8FiwiomCGkQlyJCgxEh6K56V6QOHVYcNYQC_Rb2Hm2jBAAHB4nYZzyHALoXeE8_vktlx6KJWL8dDo_7BYmc9-f0mZKGhC2HSUW0qNNNG_RSA2PVk-5BqKiGLOYKTUAsIzfpBAFLQ0HCcgJFSW6PDEmpyJrAlg4NgRjJg1JHMsg5wejjYCF2EpElySat9S4dVz4ttQIDouRq0WOArGwHdYD8mWs1JjCZGzI_AaySmlH3-dfyOsmVz60Wc2uxFExT6cZIWqnzn1xN4A0-r8NbxD6RwzhjuNRc_Gvy7dobdBt5_F8tPhKugbx_XqFfQv8xLGxRGjGzv1VrILBwlS7N95ZErTCV-T5S3MCSx6cjllurH9xMqqZUi3CY5vMEHW9EbIKMBIFewbswewXOzYBpcuxlmjZuMPSloxB4edbE_cSJY8c9-Ju2F6WvYjUBHGSOOIe5yUm_C-EUwEcrfb0Rx_Evebq1hWVQAw686u1by5QXYiuCl_qL5wuQV1gv7It7xD8e3GutsdC7TLxmg2X-zKTe3919fN7MRbJQz5fGtKXB8_7J0_9ql5_TXzfHMtQBjaHNbP0-gd8YFpcXo7xuYBiGjXZGFt8rGeZ-XI5XQa8b7xpUOEwdm-rxYX8o5s0kI1ItJRa38zrcxTTJPrfcUhbsuDMQ-r-Q-VAY&q=github+yunohost+sear => generated 0 bytes in 10109 msecs (HTTP/2.0 200) 3 headers in 0 bytes (1 switches on core 0)'
b'ERROR:searx.search:engine seedpeer : HTTP requests timeout(search duration : 10.1681249142 s, timeout: 10.0 s) : ReadTimeout'
b"ERROR:searx.search:engine torrentz : requests exception(search duration : 0.0497088432312 s, timeout: 10.0 s) : HTTPSConnectionPool(host='torrentz2.eu', port=443): Max retries exceeded with url: /search?p=0&f=st (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3e56c1450>: Failed to establish a new connection: [Errno -2] Name or service not known',))"
b'Traceback (most recent call last):'
b'  File "/opt/yunohost/searx/searx/search.py", line 160, in search_one_http_request_safe'
b'    search_results = search_one_http_request(engine, query, request_params)'
b'  File "/opt/yunohost/searx/searx/search.py", line 93, in search_one_http_request'
b'    response = send_http_request(engine, request_params)'
b'  File "/opt/yunohost/searx/searx/search.py", line 77, in send_http_request'
b"    return req(request_params['url'], **request_args)"
b'  File "/opt/yunohost/searx/searx/poolrequests.py", line 133, in get'
b"    return request('get', url, **kwargs)"
b'  File "/opt/yunohost/searx/searx/poolrequests.py", line 109, in request'
b'    response = session.request(method=method, url=url, **kwargs)'
b'  File "/opt/yunohost/searx/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request'
b'    resp = self.send(prep, **send_kwargs)'
b'  File "/opt/yunohost/searx/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send'
b'    r = adapter.send(request, **kwargs)'
b'  File "/opt/yunohost/searx/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send'
b'    raise ConnectionError(e, request=request)'
b"ConnectionError: HTTPSConnectionPool(host='torrentz2.eu', port=443): Max retries exceeded with url: /search?p=0&f=st (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3e56c1450>: Failed to establish a new connection: [Errno -2] Name or service not known',))"
b'WARNING:searx.search:engine timeout: seedpeer'
b'[pid: 3315|app: 0|req: 8/26] 93.236.2.48 () {48 vars in 3364 bytes} [Thu Dec 31 05:18:13 2020] GET /sx/?preferences=eJx1VE2P0zAQ_TXkEhUBe-CUAwIhVkLaFe1ytSb2JBlie4LttBt-PeM2aZNlOTSVx_Px3vPMBIyjTVGxVx5PKkFdfQUbsTBMKmBke8RQRU27bqzfplNhwbcjtFih3z3tC8saLFZGAihCbdGowY4t-Vj9JLez1KPqOPU4xTcfPj8M6HNWKaks-f5atw58ihhy_ex37xvylFBFHdjaJfKT1hij-vJwL0lOQRwKcoJFDYGfpxk4jIk1u8FiwiomCGkQlyJCgxEh6K56V6QOHVYcNYQC_Rb2Hm2jBAAHB4nYZzyHALoXeE8_vktlx6KJWL8dDo_7BYmc9-f0mZKGhC2HSUW0qNNNG_RSA2PVk-5BqKiGLOYKTUAsIzfpBAFLQ0HCcgJFSW6PDEmpyJrAlg4NgRjJg1JHMsg5wejjYCF2EpElySat9S4dVz4ttQIDouRq0WOArGwHdYD8mWs1JjCZGzI_AaySmlH3-dfyOsmVz60Wc2uxFExT6cZIWqnzn1xN4A0-r8NbxD6RwzhjuNRc_Gvy7dobdBt5_F8tPhKugbx_XqFfQv8xLGxRGjGzv1VrILBwlS7N95ZErTCV-T5S3MCSx6cjllurH9xMqqZUi3CY5vMEHW9EbIKMBIFewbswewXOzYBpcuxlmjZuMPSloxB4edbE_cSJY8c9-Ju2F6WvYjUBHGSOOIe5yUm_C-EUwEcrfb0Rx_Evebq1hWVQAw686u1by5QXYiuCl_qL5wuQV1gv7It7xD8e3GutsdC7TLxmg2X-zKTe3919fN7MRbJQz5fGtKXB8_7J0_9ql5_TXzfHMtQBjaHNbP0-gd8YFpcXo7xuYBiGjXZGFt8rGeZ-XI5XQa8b7xpUOEwdm-rxYX8o5s0kI1ItJRa38zrcxTTJPrfcUhbsuDMQ-r-Q-VAY&q=st => generated 72273 bytes in 10169 msecs (HTTP/2.0 200) 3 headers in 594 bytes (2 switches on core 0)'
b'ERROR:searx.search:engine seedpeer : HTTP requests timeout(search duration : 10.2234928608 s, timeout: 10.0 s) : ReadTimeout'
b'[pid: 3315|app: 0|req: 9/27] 93.236.2.48 () {46 vars in 1501 bytes} [Thu Dec 31 05:18:23 2020] GET /sx/static/themes/oscar/css/logicodev-dark.min.css => generated 13348 bytes in 17 msecs via sendfile() (HTTP/2.0 200) 9 headers in 336 bytes (0 switches on core 0)'
b'[pid: 3315|app: 0|req: 10/28] 93.236.2.48 () {46 vars in 1454 bytes} [Thu Dec 31 05:18:23 2020] GET /sx/static/js/jquery-1.11.1.min.js => generated 95786 bytes in 6 msecs via sendfile() (HTTP/2.0 200) 9 headers in 349 bytes (1 switches on core 0)'
b'[pid: 3315|app: 0|req: 11/29] 93.236.2.48 () {46 vars in 1460 bytes} [Thu Dec 31 05:18:23 2020] GET /sx/static/js/typeahead.bundle.min.js => generated 29675 bytes in 16 msecs via sendfile() (HTTP/2.0 200) 9 headers in 350 bytes (1 switches on core 0)'
b'[pid: 3315|app: 0|req: 12/30] 93.236.2.48 () {46 vars in 1456 bytes} [Thu Dec 31 05:18:23 2020] GET /sx/static/js/require-2.1.15.min.js => generated 15219 bytes in 6 msecs via sendfile() (HTTP/2.0 200) 9 headers in 349 bytes (0 switches on core 0)'
b'[pid: 3315|app: 0|req: 13/31] 93.236.2.48 () {46 vars in 1464 bytes} [Thu Dec 31 05:18:23 2020] GET /sx/static/themes/oscar/js/searx.min.js => generated 4836 bytes in 7 msecs via sendfile() (HTTP/2.0 200) 9 headers in 347 bytes (0 switches on core 0)'
b'[pid: 3315|app: 0|req: 14/32] 93.236.2.48 () {46 vars in 1486 bytes} [Thu Dec 31 05:18:23 2020] GET /sx/static/plugins/js/search_on_category_select.js => generated 771 bytes in 8 msecs via sendfile() (HTTP/2.0 200) 9 headers in 342 bytes (0 switches on core 0)'
b'[pid: 3314|app: 0|req: 6/33] 93.236.2.48 () {46 vars in 1465 bytes} [Thu Dec 31 05:18:23 2020] GET /sx/static/css/bootstrap.min.css => generated 110477 bytes in 171 msecs via sendfile() (HTTP/2.0 200) 9 headers in 337 bytes (0 switches on core 0)'
b'[pid: 3317|app: 0|req: 12/34] 93.236.2.48 () {46 vars in 1487 bytes} [Thu Dec 31 05:18:23 2020] GET /sx/static/themes/oscar/css/leaflet.min.css => generated 8027 bytes in 187 msecs via sendfile() (HTTP/2.0 200) 9 headers in 334 bytes (0 switches on core 0)'
b'[pid: 3314|app: 0|req: 7/35] 93.236.2.48 () {42 vars in 1494 bytes} [Thu Dec 31 05:18:24 2020] GET /sx/static/themes/oscar/img/favicon.png => generated 1853 bytes in 5 msecs via sendfile() (HTTP/2.0 200) 9 headers in 318 bytes (0 switches on core 0)'
b'[pid: 3316|app: 0|req: 3/36] 93.236.2.48 () {46 vars in 1446 bytes} [Thu Dec 31 05:18:23 2020] GET /sx/static/js/bootstrap.min.js => generated 31819 bytes in 207 msecs via sendfile() (HTTP/2.0 200) 9 headers in 349 bytes (0 switches on core 0)'
b'[pid: 3315|app: 0|req: 15/37] 93.236.2.48 () {46 vars in 1540 bytes} [Thu Dec 31 05:18:25 2020] GET /sx/static/fonts/glyphicons-halflings-regular.woff => generated 23320 bytes in 7 msecs via sendfile() (HTTP/2.0 200) 9 headers in 319 bytes (1 switches on core 0)'
Tue Jun 22 23:57:54 2021 - ...brutally killing workers...
Tue Jun 22 23:57:55 2021 - worker 1 buried after 1 seconds
Tue Jun 22 23:57:55 2021 - worker 2 buried after 1 seconds
Tue Jun 22 23:57:55 2021 - worker 3 buried after 1 seconds
Tue Jun 22 23:57:55 2021 - worker 4 buried after 1 seconds
Tue Jun 22 23:57:55 2021 - binary reloading uWSGI...
Tue Jun 22 23:57:55 2021 - chdir() to /
Tue Jun 22 23:57:55 2021 - closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
Tue Jun 22 23:57:55 2021 - found fd 3 mapped to socket 0 (/run/uwsgi/app/searx/socket)
Tue Jun 22 23:57:55 2021 - running /usr/bin/uwsgi-core
[uWSGI] getting INI configuration from /usr/share/uwsgi/conf/default.ini
realpath() of /etc/uwsgi/apps-enabled/searx.ini failed: No such file or directory [core/utils.c line 3654]`

Thanks and regards,
Hyper

**Comment by demitasse-1** [comment]
I am having the same problem. I migrated to bullseye and ran the python repair migration afterwards. I did both of the migrations from the GUI Admin. All my other yunohost apps are fine and survived the migration with no issue, just searx is giving a 502 error. 

Here's the logs


LOGFILE: journalctl
-- Journal begins at Mon 2022-08-22 19:27:37 UTC, ends at Tue 2022-08-23 04:07:31 UTC. --
Aug 23 03:47:26 systemd[1]: /etc/systemd/system/uwsgi-app@.service:13: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
Aug 23 03:48:09 systemd[1]: /etc/systemd/system/uwsgi-app@.service:13: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
Aug 23 03:51:24 systemd[1]: Stopping searx uWSGI app...
Aug 23 03:51:25 systemd[1]: uwsgi-app@searx.service: Succeeded.
Aug 23 03:51:25 systemd[1]: Stopped searx uWSGI app.
-- Boot 1129beb224844a88bbb86925c80a64f1 --
Aug 23 03:51:57 systemd[1]: Starting searx uWSGI app...
Aug 23 03:51:57 uwsgi[602]: [uWSGI] getting INI configuration from /etc/uwsgi/apps-available/searx.ini
Aug 23 03:51:57 systemd[1]: Started searx uWSGI app.
Aug 23 04:01:05 systemd[1]: Stopping searx uWSGI app...
Aug 23 04:01:06 systemd[1]: uwsgi-app@searx.service: Succeeded.
Aug 23 04:01:06 systemd[1]: Stopped searx uWSGI app.
Aug 23 04:01:06 systemd[1]: uwsgi-app@searx.service: Consumed 1.759s CPU time.
-- Boot fcc7889791464112b553545d5dc32205 --
Aug 23 04:01:41 systemd[1]: Starting searx uWSGI app...
Aug 23 04:01:41 uwsgi[605]: [uWSGI] getting INI configuration from /etc/uwsgi/apps-available/searx.ini
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Main process exited, code=exited, status=1/FAILURE
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Failed with result 'exit-code'.
Aug 23 04:01:41 systemd[1]: Failed to start searx uWSGI app.
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Scheduled restart job, restart counter is at 1.
Aug 23 04:01:41 systemd[1]: Stopped searx uWSGI app.
Aug 23 04:01:41 systemd[1]: Starting searx uWSGI app...
Aug 23 04:01:41 uwsgi[743]: [uWSGI] getting INI configuration from /etc/uwsgi/apps-available/searx.ini
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Main process exited, code=exited, status=1/FAILURE
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Failed with result 'exit-code'.
Aug 23 04:01:41 systemd[1]: Failed to start searx uWSGI app.
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Scheduled restart job, restart counter is at 2.
Aug 23 04:01:41 systemd[1]: Stopped searx uWSGI app.
Aug 23 04:01:41 systemd[1]: Starting searx uWSGI app...
Aug 23 04:01:41 uwsgi[862]: [uWSGI] getting INI configuration from /etc/uwsgi/apps-available/searx.ini
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Main process exited, code=exited, status=1/FAILURE
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Failed with result 'exit-code'.
Aug 23 04:01:41 systemd[1]: Failed to start searx uWSGI app.
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Scheduled restart job, restart counter is at 3.
Aug 23 04:01:41 systemd[1]: Stopped searx uWSGI app.
Aug 23 04:01:41 systemd[1]: Starting searx uWSGI app...
Aug 23 04:01:41 uwsgi[907]: [uWSGI] getting INI configuration from /etc/uwsgi/apps-available/searx.ini
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Main process exited, code=exited, status=1/FAILURE
Aug 23 04:01:41 systemd[1]: uwsgi-app@searx.service: Failed with result 'exit-code'.
Aug 23 04:01:41 systemd[1]: Failed to start searx uWSGI app.
Aug 23 04:01:42 systemd[1]: uwsgi-app@searx.service: Scheduled restart job, restart counter is at 4.
Aug 23 04:01:42 systemd[1]: Stopped searx uWSGI app.
Aug 23 04:01:42 systemd[1]: Starting searx uWSGI app...
Aug 23 04:01:42 uwsgi[1106]: [uWSGI] getting INI configuration from /etc/uwsgi/apps-available/searx.ini
Aug 23 04:01:42 systemd[1]: uwsgi-app@searx.service: Main process exited, code=exited, status=1/FAILURE
Aug 23 04:01:42 systemd[1]: uwsgi-app@searx.service: Failed with result 'exit-code'.
Aug 23 04:01:42 systemd[1]: Failed to start searx uWSGI app.
Aug 23 04:01:42 systemd[1]: uwsgi-app@searx.service: Scheduled restart job, restart counter is at 5.
Aug 23 04:01:42 systemd[1]: Stopped searx uWSGI app.
Aug 23 04:01:42 systemd[1]: uwsgi-app@searx.service: Start request repeated too quickly.
Aug 23 04:01:42 systemd[1]: uwsgi-app@searx.service: Failed with result 'exit-code'.
Aug 23 04:01:42 systemd[1]: Failed to start searx uWSGI app.

LOGFILE: /var/log/uwsgi/searx/searx.log
*** dumping internal routing table ***
[rule: 0] action: fixpathinfo:
*** end of the internal routing table ***
chdir() to /opt/yunohost/searx/searx/
chdir(): No such file or directory [core/uwsgi.c line 2625]
*** Starting uWSGI 2.0.19.1-debian (64bit) on [Tue Aug 23 04:01:41 2022] ***
compiled with version: 10.2.1 20210110 on 11 June 2021 09:08:33
os: Linux-5.10.0-17-cloud-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13)
nodename: narrativerry.xyz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /usr/bin/uwsgi-core
*** dumping internal routing table ***
[rule: 0] action: fixpathinfo:
*** end of the internal routing table ***
chdir() to /opt/yunohost/searx/searx/
chdir(): No such file or directory [core/uwsgi.c line 2625]
*** Starting uWSGI 2.0.19.1-debian (64bit) on [Tue Aug 23 04:01:41 2022] ***
compiled with version: 10.2.1 20210110 on 11 June 2021 09:08:33
os: Linux-5.10.0-17-cloud-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13)
nodename: narrativerry.xyz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /usr/bin/uwsgi-core
*** dumping internal routing table ***
[rule: 0] action: fixpathinfo:
*** end of the internal routing table ***
chdir() to /opt/yunohost/searx/searx/
chdir(): No such file or directory [core/uwsgi.c line 2625]
*** Starting uWSGI 2.0.19.1-debian (64bit) on [Tue Aug 23 04:01:42 2022] ***
compiled with version: 10.2.1 20210110 on 11 June 2021 09:08:33
os: Linux-5.10.0-17-cloud-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13)
nodename: narrativerry.xyz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /
detected binary path: /usr/bin/uwsgi-core
*** dumping internal routing table ***
[rule: 0] action: fixpathinfo:
*** end of the internal routing table ***
chdir() to /opt/yunohost/searx/searx/
chdir(): No such file or directory [core/uwsgi.c line 2625]

Thanks in advance for any help. I appreciate it.

**Comment by demitasse-1** [comment]
I was able to get it working by uninstalling searx and reinstalling.

**Comment by rosbeef** [comment]
there is a bug here /opt/yunohost/searx/searx/
there is 2 times searx
