### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by xpd259** [YunoHost-Apps/searx_ynh#12]
hiya, I'm having issues installing.
when I try to install I get the following

```
root@trinity:/home/thadeus/searx# yunohost app install https://github.com/YunoHost-Apps/searx_ynh
Available domains:
- speaksthegeek.co.uk
- social.speaksthegeek.co.uk
Choose a domain for Searx (default: speaksthegeek.co.uk): 
Choose a path for Searx (default: /searx): 
Is it a public Searx site ? [0 | 1] (default: 1): 0
Warning: Traceback (most recent call last):
Warning:   File "<string>", line 1, in <module>
Warning:   File "/usr/lib/python3.4/json/__init__.py", line 265, in load
Warning:     return loads(fp.read(),
Warning:   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
Warning:     return codecs.ascii_decode(input, self.errors)[0]
Warning: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 197: ordinal not in range(128)
Warning: !!
Warning:   searx's script has encountered an error. Its execution was cancelled.
Warning: !!
Warning: 
Warning: /etc/uwsgi/apps-available/searx.ini wasn't deleted because it doesn't exist.
Warning: E: Unable to locate package searx-ynh-deps
Warning: /opt/yunohost/searx wasn't deleted because it doesn't exist.
Warning: /etc/nginx/conf.d/speaksthegeek.co.uk.d/searx.conf wasn't deleted because it doesn't exist.
Warning: The user searx was not found
```

Sorry I'm not able to diagnose this.

**Comment by xpd259** [comment]
oops never mind, it seems my Database is corrupted and isn't loading 
I'll close the issue and reopen if I need to 

sorry
