### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by kay0u** [YunoHost-Apps/searx_ynh#43]
I can't insall Searx in my fresh Yunohost.

You can find some logs here: https://paste.yunohost.org/raw/cojelemuwe

It crashed here:
```
Exception: Version mismatch: this is the 'cffi' package version 1.12.1, located in '/tmp/pip-build-env-yuz5hD/overlay/lib/python2.7/site-packages/cffi/api.pyc'.  When we import the top-level '_cffi_backend' extension module, we get version 1.9.1, located in '/usr/lib/python2.7/dist-packages/_cffi_backend.arm-linux-gnueabihf.so'.  The two versions should be equal; check your installation.
```

**Comment by Santosh-Sah** [comment]
For me too, its failing on fresh installation.

`2019-03-01 21:17:23,388: DEBUG -     Exception: Version mismatch: this is the 'cffi' package version 1.12.2, located in '/tmp/pip-build-env-NBSAoO/overlay/lib/python2.7/site-packages/cffi/api.pyc'.  When we import the top-level '_cffi_backend' extension module, we get version 1.9.1, located in '/usr/lib/python2.7/dist-packages/_cffi_backend.arm-linux-gnueabihf.so'.  The two versions should be equal; check your installation.
2019-03-01 21:17:23,390: DEBUG - 
2019-03-01 21:17:23,391: DEBUG -     ----------------------------------------
2019-03-01 21:17:23,593: WARNING - Command "/opt/yunohost/searx/bin/python2 /opt/yunohost/searx/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpNmF9qW" failed with error code 1 in /tmp/pip-install-PkOUj_/cryptography
2019-03-01 21:17:24,300: DEBUG - + ynh_exit_properly
2019-03-01 21:17:24,302: WARNING - !!
2019-03-01 21:17:24,328: DEBUG - + local exit_code=1
2019-03-01 21:17:24,329: WARNING -   searx's script has encountered an error. Its execution was cancelled.
2019-03-01 21:17:24,332: DEBUG - + '[' 1 -eq 0 ']'
2019-03-01 21:17:24,333: WARNING - !!
2019-03-01 21:17:24,336: DEBUG - + trap '' EXIT
2019-03-01 21:17:24,338: WARNING - 
2019-03-01 21:17:24,340: DEBUG - + set +eu
2019-03-01 21:17:24,342: DEBUG - + echo -e '!!\n  searx'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-03-01 21:17:24,343: DEBUG - + type -t ynh_clean_setup
2019-03-01 21:17:24,344: DEBUG - + ynh_die
2019-03-01 21:17:24,345: DEBUG - + echo ''
2019-03-01 21:17:24,347: DEBUG - + exit 1`

Is there any workaround available?

**Comment by deville-m** [comment]
I think I know the issue, or at least the main one.
If you look at the file [app.src](https://github.com/YunoHost-Apps/searx_ynh/blob/master/conf/app.src), you'll see that the SOURCE_URL is broken; it doesn't exists anymore :(
You can always fork the project try to find a working tar.gz link and replace it.

**Comment by Santosh-Sah** [comment]
I tried editing app.src but still its failing
Fork: https://github.com/Santosh-Sah/searx_ynh 

Errors:
`2019-03-23 21:00:41,171: DEBUG - Collecting cryptography>=1.9 (from pyopenssl==17.4.0->-r /opt/yunohost/searx/requirements-ynh.txt (line 8))
2019-03-23 21:00:47,494: DEBUG -   Using cached https://files.pythonhosted.org/packages/07/ca/bc827c5e55918ad223d59d299fff92f3563476c3b00d0a9157d9c0217449/cryptography-2.6.1.tar.gz
2019-03-23 21:00:48,500: DEBUG -   Installing build dependencies: started
2019-03-23 21:01:15,899: DEBUG -   Installing build dependencies: finished with status 'done'
2019-03-23 21:01:15,901: DEBUG -   Getting requirements to build wheel: started
2019-03-23 21:01:20,318: DEBUG -   Getting requirements to build wheel: finished with status 'done'
2019-03-23 21:01:20,320: DEBUG -     Preparing wheel metadata: started
2019-03-23 21:01:24,335: DEBUG -     Preparing wheel metadata: finished with status 'error'
2019-03-23 21:01:24,337: DEBUG -     Complete output from command /opt/yunohost/searx/bin/python2 /opt/yunohost/searx/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpmFYmoV:
2019-03-23 21:01:24,338: DEBUG -     Traceback (most recent call last):
2019-03-23 21:01:24,340: DEBUG -       File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
2019-03-23 21:01:24,341: DEBUG -         main()
2019-03-23 21:01:24,342: DEBUG -       File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
2019-03-23 21:01:24,343: DEBUG -         json_out['return_val'] = hook(**hook_input['kwargs'])
2019-03-23 21:01:24,345: DEBUG -       File "/opt/yunohost/searx/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
2019-03-23 21:01:24,346: DEBUG -         return hook(metadata_directory, config_settings)
2019-03-23 21:01:24,347: DEBUG -       File "/opt/yunohost/searx/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 140, in prepare_metadata_for_build_wheel
2019-03-23 21:01:24,349: DEBUG -         self.run_setup()
2019-03-23 21:01:24,350: DEBUG -       File "/opt/yunohost/searx/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 211, in run_setup
2019-03-23 21:01:24,351: DEBUG -         self).run_setup(setup_script=setup_script)
2019-03-23 21:01:24,352: DEBUG -       File "/opt/yunohost/searx/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 126, in run_setup
2019-03-23 21:01:24,353: DEBUG -         exec(compile(code, __file__, 'exec'), locals())
2019-03-23 21:01:24,355: DEBUG -       File "setup.py", line 324, in <module>
2019-03-23 21:01:24,356: DEBUG -         **keywords_with_side_effects(sys.argv)
2019-03-23 21:01:24,357: DEBUG -       File "/opt/yunohost/searx/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
2019-03-23 21:01:24,359: DEBUG -         return distutils.core.setup(**attrs)
2019-03-23 21:01:24,360: DEBUG -       File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
2019-03-23 21:01:24,361: DEBUG -         _setup_distribution = dist = klass(attrs)
2019-03-23 21:01:24,363: DEBUG -       File "/opt/yunohost/searx/local/lib/python2.7/site-packages/setuptools/dist.py", line 447, in __init__
2019-03-23 21:01:24,364: DEBUG -         k: v for k, v in attrs.items()
2019-03-23 21:01:24,365: DEBUG -       File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
2019-03-23 21:01:24,366: DEBUG -         self.finalize_options()
2019-03-23 21:01:24,368: DEBUG -       File "/opt/yunohost/searx/local/lib/python2.7/site-packages/setuptools/dist.py", line 739, in finalize_options
2019-03-23 21:01:24,369: DEBUG -         ep.load()(self, ep.name, value)
2019-03-23 21:01:24,370: DEBUG -       File "/tmp/pip-build-env-UF3Neg/overlay/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 217, in cffi_modules
2019-03-23 21:01:24,371: DEBUG -         add_cffi_module(dist, cffi_module)
2019-03-23 21:01:24,373: DEBUG -       File "/tmp/pip-build-env-UF3Neg/overlay/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
2019-03-23 21:01:24,374: DEBUG -         execfile(build_file_name, mod_vars)
2019-03-23 21:01:24,375: DEBUG -       File "/tmp/pip-build-env-UF3Neg/overlay/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
2019-03-23 21:01:24,376: DEBUG -         exec(code, glob, glob)
2019-03-23 21:01:24,378: DEBUG -       File "src/_cffi_src/build_openssl.py", line 106, in <module>
2019-03-23 21:01:24,379: DEBUG -         extra_link_args=extra_link_args(compiler_type()),
2019-03-23 21:01:24,380: DEBUG -       File "src/_cffi_src/utils.py", line 57, in build_ffi_for_binding
2019-03-23 21:01:24,381: DEBUG -         extra_link_args=extra_link_args,
2019-03-23 21:01:24,382: DEBUG -       File "src/_cffi_src/utils.py", line 65, in build_ffi
2019-03-23 21:01:24,384: DEBUG -         ffi = FFI()
2019-03-23 21:01:24,385: DEBUG -       File "/tmp/pip-build-env-UF3Neg/overlay/lib/python2.7/site-packages/cffi/api.py", line 56, in __init__
2019-03-23 21:01:24,386: DEBUG -         backend.__version__, backend.__file__))
2019-03-23 21:01:24,387: DEBUG -     Exception: Version mismatch: this is the 'cffi' package version 1.12.2, located in '/tmp/pip-build-env-UF3Neg/overlay/lib/python2.7/site-packages/cffi/api.pyc'.  When we import the top-level '_cffi_backend' extension module, we get version 1.9.1, located in '/usr/lib/python2.7/dist-packages/_cffi_backend.arm-linux-gnueabihf.so'.  The two versions should be equal; check your installation.
2019-03-23 21:01:24,389: DEBUG - 
2019-03-23 21:01:24,390: DEBUG -     ----------------------------------------
2019-03-23 21:01:24,592: WARNING - Command "/opt/yunohost/searx/bin/python2 /opt/yunohost/searx/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpmFYmoV" failed with error code 1 in /tmp/pip-install-xvGcKY/cryptography
2019-03-23 21:01:25,299: DEBUG - + ynh_exit_properly
2019-03-23 21:01:25,300: WARNING - !!
2019-03-23 21:01:25,303: DEBUG - + local exit_code=1
2019-03-23 21:01:25,304: WARNING -   searx's script has encountered an error. Its execution was cancelled.
2019-03-23 21:01:25,307: DEBUG - + '[' 1 -eq 0 ']'
2019-03-23 21:01:25,308: WARNING - !!
2019-03-23 21:01:25,311: DEBUG - + trap '' EXIT
2019-03-23 21:01:25,312: WARNING - 
2019-03-23 21:01:25,315: DEBUG - + set +eu
2019-03-23 21:01:25,316: DEBUG - + echo -e '!!\n  searx'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-03-23 21:01:25,317: DEBUG - + type -t ynh_clean_setup
2019-03-23 21:01:25,318: DEBUG - + ynh_die
2019-03-23 21:01:25,319: DEBUG - + echo ''
2019-03-23 21:01:25,320: DEBUG - + exit 1
`

**Comment by maniackcrudelis** [comment]
I just tried to install Searx on a VM, I do not reproduce your error.
Everything went fine, searx works.
What's your configuration ?

**Comment by kay0u** [comment]
I'm trying to install it on a ARM board.

**Comment by Santosh-Sah** [comment]
I have installed on Raspberry pi running on yunohost 3.4.2.4

**Comment by Roboron3042** [comment]
I'm also trying to install searx on a Raspberry Pi (YunoHost 3.6.4.3) and getting this error.

**Comment by Santosh-Sah** [comment]
I wanted to say the same thing, after installing python-ciff manually, it's working fine

**Comment by AkselRocks** [comment]
can this issue be closed?

**Comment by kay0u** [comment]
I think so :-)
