### ISSUE TITLE
Error: "500" Internal Server Error

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/searx_ynh#97]
- Hardware: VPS bought online 
- YunoHost version: 4.2.8.3 (stable)
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

I get this error when trying to access the service via the yunohost panel. 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 484, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 600, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/service.py", line 516, in service_log
    result[log_path] = _tail(log_path, number)
  File "/usr/lib/moulinette/yunohost/service.py", line 755, in _tail
    lines = f.read().splitlines()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 803227824: invalid continuation byte

```
![2021-10-17_12-27](https://user-images.githubusercontent.com/38043315/137623241-e22fed8f-a7b6-4259-a45d-e84cdba115a5.png)

**Comment by tootbrute** [comment]
I have the same problem.

**Comment by yalh76** [comment]
have you tried with the last version
